package tree

import (
	"fmt"
	"runtime"
)

func AA() {
	fmt.Println("GOOS", runtime.GOOS, "GOARCH", runtime.GOARCH)
	fmt.Println("go:build go1.18 +build go1.18")
}

const add = `
//go:build go1.18
// +build go1.18

// Code generated by gengoos.go using 'go generate'. DO NOT EDIT.

//go:build windows

//go:build amd64

`
